spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rick_morty
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
